#!/bin/sh
set -eu

ROOT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
INFRA_ENV="$ROOT_DIR/infra/.env"
BACKEND_ENV="$ROOT_DIR/backend/.env"
FRONTEND_ENV="$ROOT_DIR/frontend/.env"

is_used() {
  port="$1"
  if lsof -nP -iTCP:"$port" -sTCP:LISTEN >/dev/null 2>&1; then
    return 0
  fi
  return 1
}

pick_port() {
  for port in "$@"; do
    if ! is_used "$port"; then
      printf "%s" "$port"
      return 0
    fi
  done

  return 1
}

MYSQL_HOST_PORT=$(pick_port 3306 13306 13316 13326 13336)
BACKEND_HOST_PORT=$(pick_port 8000 18000 18001 18002 18003)
FRONTEND_HOST_PORT=$(pick_port 5173 15173 15183 15193 15203)
MINIO_API_HOST_PORT=$(pick_port 9000 19000 19010 19020)
MINIO_CONSOLE_HOST_PORT=$(pick_port 9001 19001 19011 19021)
MAILPIT_SMTP_HOST_PORT=$(pick_port 1025 11025 1125 12025)
MAILPIT_UI_HOST_PORT=$(pick_port 8025 18025 18026 18125)

DB_DATABASE="yado_education"
DB_USERNAME="yado"
DB_PASSWORD="secret"
DB_ROOT_PASSWORD="root"
MINIO_ROOT_USER="minioadmin"
MINIO_ROOT_PASSWORD="minioadmin"
AWS_BUCKET="yado-education"
AWS_DEFAULT_REGION="ap-northeast-1"

APP_URL="http://localhost:${BACKEND_HOST_PORT}"
FRONTEND_URL="http://localhost:${FRONTEND_HOST_PORT}"
SANCTUM_STATEFUL_DOMAINS="localhost:${FRONTEND_HOST_PORT},127.0.0.1:${FRONTEND_HOST_PORT},0.0.0.0:${FRONTEND_HOST_PORT},localhost:${BACKEND_HOST_PORT},127.0.0.1:${BACKEND_HOST_PORT},0.0.0.0:${BACKEND_HOST_PORT}"
AWS_ENDPOINT="http://minio:9000"
AWS_URL="http://localhost:${MINIO_API_HOST_PORT}/${AWS_BUCKET}"
MAIL_HOST="mailpit"
MAIL_PORT=1025

if command -v php >/dev/null 2>&1; then
  APP_KEY=$(php -r 'echo "base64:".base64_encode(random_bytes(32));')
else
  APP_KEY=""
fi

cat > "$INFRA_ENV" <<ENV
MYSQL_HOST_PORT=${MYSQL_HOST_PORT}
BACKEND_HOST_PORT=${BACKEND_HOST_PORT}
FRONTEND_HOST_PORT=${FRONTEND_HOST_PORT}
MINIO_API_HOST_PORT=${MINIO_API_HOST_PORT}
MINIO_CONSOLE_HOST_PORT=${MINIO_CONSOLE_HOST_PORT}
MAILPIT_SMTP_HOST_PORT=${MAILPIT_SMTP_HOST_PORT}
MAILPIT_UI_HOST_PORT=${MAILPIT_UI_HOST_PORT}

DB_DATABASE=${DB_DATABASE}
DB_USERNAME=${DB_USERNAME}
DB_PASSWORD=${DB_PASSWORD}
DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}

MINIO_ROOT_USER=${MINIO_ROOT_USER}
MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}

APP_URL=${APP_URL}
FRONTEND_URL=${FRONTEND_URL}
SANCTUM_STATEFUL_DOMAINS=${SANCTUM_STATEFUL_DOMAINS}
AWS_URL=${AWS_URL}
ENV

cat > "$BACKEND_ENV" <<ENV
APP_NAME="社内教育システム"
APP_ENV=local
APP_KEY=${APP_KEY}
APP_DEBUG=true
APP_URL=${APP_URL}
FRONTEND_URL=${FRONTEND_URL}

APP_LOCALE=ja
APP_FALLBACK_LOCALE=ja
APP_FAKER_LOCALE=ja_JP
APP_TIMEZONE=Asia/Tokyo

APP_MAINTENANCE_DRIVER=file

BCRYPT_ROUNDS=12

LOG_CHANNEL=stack
LOG_STACK=single
LOG_DEPRECATIONS_CHANNEL=null
LOG_LEVEL=debug

DB_CONNECTION=mysql
DB_HOST=mysql
DB_PORT=3306
DB_DATABASE=${DB_DATABASE}
DB_USERNAME=${DB_USERNAME}
DB_PASSWORD=${DB_PASSWORD}

SESSION_DRIVER=database
SESSION_LIFETIME=120
SESSION_ENCRYPT=false
SESSION_PATH=/
SESSION_COOKIE=yado_education_session
SESSION_DOMAIN=
SESSION_SECURE_COOKIE=false
SESSION_SAME_SITE=lax

SANCTUM_STATEFUL_DOMAINS=${SANCTUM_STATEFUL_DOMAINS}

BROADCAST_CONNECTION=log
FILESYSTEM_DISK=s3
QUEUE_CONNECTION=database

CACHE_STORE=database

MAIL_MAILER=smtp
MAIL_SCHEME=null
MAIL_HOST=${MAIL_HOST}
MAIL_PORT=${MAIL_PORT}
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_FROM_ADDRESS="noreply@yado-education.local"
MAIL_FROM_NAME="社内教育システム"

AWS_ACCESS_KEY_ID=${MINIO_ROOT_USER}
AWS_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}
AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
AWS_BUCKET=${AWS_BUCKET}
AWS_USE_PATH_STYLE_ENDPOINT=true
AWS_ENDPOINT=${AWS_ENDPOINT}
AWS_URL=${AWS_URL}

JUDGE_IMAGE=yado-judge-runner:latest
JUDGE_CPU=0.5
JUDGE_TIME_LIMIT_SEC=5
JUDGE_MEMORY_LIMIT_MB=256

VITE_APP_NAME="社内教育システム"
ENV

cat > "$FRONTEND_ENV" <<ENV
VITE_API_BASE_URL=${APP_URL}
ENV

cat <<INFO
[完了] 環境ファイルを生成しました。
- infra/.env
- backend/.env
- frontend/.env

[使用ポート]
- MySQL: ${MYSQL_HOST_PORT}
- Backend API: ${BACKEND_HOST_PORT}
- Frontend: ${FRONTEND_HOST_PORT}
- MinIO API: ${MINIO_API_HOST_PORT}
- MinIO Console: ${MINIO_CONSOLE_HOST_PORT}
- Mailpit SMTP: ${MAILPIT_SMTP_HOST_PORT}
- Mailpit UI: ${MAILPIT_UI_HOST_PORT}
INFO
